[build]
  publish = "build"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "true"

# DeepSeek API 代理 - 修复路径映射
[[redirects]]
  from = "/api/deepseek/v1/*"
  to = "https://api.deepseek.com/v1/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization"}

# DeepSeek API 根路径代理
[[redirects]]
  from = "/api/deepseek/*"
  to = "https://api.deepseek.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization"}

# RAG API 代理 (如果需要)
[[redirects]]
  from = "/api/rag/*"
  to = "http://localhost:8000/:splat"
  status = 200
  force = false

# SPA 路由支持
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 安全头配置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.deepseek.com https://*.deepseek.com"

# 静态资源缓存
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 数据文件缓存
[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# 培养方案文件缓存
[[headers]]
  for = "/培养方案/*"
  [headers.values]
    Cache-Control = "public, max-age=7200" 